subject = "Название предмета"
description = "Лекции"
term = 1 # номер семестра
authors = [
  "Егор Смирнов",
  "Артём Рудяк",
  "Артём Соловьёв",
  "Александр Храмов",
  "Роберт Толстов",
  "Данила Григорьев",
  "Михаил Чертков",
  "Виктория Лазарева",
  "Вадим Карасёв",
  "Артём Кудяков",
  "Радомир Тюменцев",
  "Александр Железко",
  "Иван Архипов",
  "Михаил Леонтьев",
  "Маргарита Потапкина"
]

[sections]
numbering = true
prefix = "Лекция "
sections = [
  "Тема 1.",
  "Тема 2.",
]

